### PR TITLE
Fix #29 Non array parameters not accepted when using JSONRPC

### LINKED ISSUE #29: Non array parameters not accepted when using JSONRPC
At the moment array parameters are enforced. That's fine as long as we use rpc2 for both client and server, but other JSONRPC libraries do not enforce it and thus requests are not properly handled.

### PR DESCRIPTION
**Pull request by plaili**
don't enforce array parameters and accept non arrays

I am pretty new to Go so maybe there is a more elegant solution than to double things, but it is working...

### CODE REVIEW

**Comment by cenkalti** [comment]
Thanks @plaili . Can you please add a test to https://github.com/cenkalti/rpc2/blob/master/jsonrpc/jsonrpc_test.go ?

**Comment by plaili** [comment]
@cenkalti I will try what I can do but actually the problem was only reproducible with a "foreign" client, because I could not produce non-array params before. Would be great if you could merge already before that.

**Comment by plaili** [comment]
@cenkalti: I think it could only be checked by inspecting the underlying JSON string... the important thing IMHO is that the existing test for named and positional params still work.

**Comment by cenkalti** [comment]
I think this PR breaks backwards compatibility because of this line:
https://github.com/cenkalti/rpc2/pull/31/files#diff-29bf6a93fbf40bb957a35d09fc2e1566d3f30bae739eb133ed16d8e8b42786afL163

After merging this, tests are still passing but the behavior has changed. Named parameters are not passed inside a list anymore. There are existing users of this library and I don't want to break their programs.

This library is a fork of original net/rpc package which itself is a JSON-RPC 1.0 implementation.
JSON-RPC 1.0 spec defines that arguments' type is a list.

Implementing JSON-RPC 2.0 is too much work and I am against doing it in this package. 

If you want to use JSON-RPC 2.0 please use another package, this library is not suitable for that job. I'll also revert the PR #28.

**Comment by plaili** [comment]
@cenkalti Fair enough. Would it be fine for you if I published my changes as jasonrpc2 to be used with your rpc2?

**Comment by cenkalti** [comment]
Yeah, go for it!

**Pull request closed without merging**
