### PR TITLE
Blocking request handler

### PR DESCRIPTION
**Pull request by hzhou8**
In some situation the order of request/response handling is
important. However, in current implementation the order can be
broken: request/response come from same connection can be handled
in random order because request handler is called in a new thread.
This patch changes that behavior by calling the handler in the same
context, to ensure the ordering.

### CODE REVIEW

**Comment by cenkalti** [comment]
I would like to keep async behavior. Concurrency is one of the biggest features of Go. You should find another way to serialize your calls.

**Comment by hzhou8** [comment]
@cenkalti I think it would be better to leave the decision to the user of this lib to decide. If they want async behavior they can always do it in the handler and return immediately. The current approach forces users to come up with their own way to serialize between the request handler, just to solve a problem created by the async processing here unnecessarily, with unnecessary cost introduced by whatever sync mechanism between threads. So I think simply do the sync processing here would be more generic.

**Comment by hzhou8** [comment]
In fact, in some situation it is not even possible for the user to do sync, when information is not available in the message itself, but only implicit in the order the messages come.

A related example use case is discussed here: https://mail.openvswitch.org/pipermail/ovs-discuss/2017-March/043858.html

**Comment by cenkalti** [comment]
The use case you mentioned is perfectly valid but what this PR does is basically removing the concurrency from the implementation. I can only accept this if you make it optional without changing the behavior for current users of this package.

**Comment by hzhou8** [comment]
Agree, backward-compatibility makes sense. I'll come up with an option.

**Comment by hzhou8** [comment]
Hi, here is the new patch which makes the behavior optional: https://github.com/cenkalti/rpc2/pull/14

**Pull request closed without merging**
